/**
 * Zero mutators — every write in the application.
 *
 * ## The rule these are all built around
 *
 * A mutator must never perform network I/O. It is a fast, purely-local,
 * transactional operation. Gmail side effects are recorded as rows in the
 * `outbox` table *inside the same transaction* as the user-visible state
 * change, and drained later by the C++ engine.
 *
 * That is what makes optimistic UI correct rather than a lie:
 *
 *   - The local write lands in the same frame, so the UI moves instantly.
 *   - The state change and its remote intent commit atomically, so a crash can
 *     never leave the mailbox archived locally but not on Gmail.
 *   - The outbox row is durable and retryable, so a flaky network is a delay
 *     rather than a lost operation.
 *
 * ## Life of a mutation
 *
 * Each mutator runs twice. First on the client against the local store, where
 * its effects are immediately visible. Then on the server against Postgres,
 * where it is authoritative. The server's result replicates back and replaces
 * the client's optimistic guess. Reads inside a mutator see only local data on
 * the client (`tx.location === 'client'`) and all data on the server.
 */

import {defineMutator, defineMutators} from '@rocicorp/zero'
import {z} from 'zod'
import {messageLabelId} from './ids.ts'
import {zql} from './schema.ts'

/**
 * Arguments shared by every outbox-producing mutator.
 *
 * `idempotencyKey` is generated by the *client* (`crypto.randomUUID()`) and
 * passed through. Because the mutator runs on both client and server with the
 * same key, a retried mutation collapses onto the same outbox row instead of
 * sending the same Gmail call twice.
 */
const outboxArgs = {
  accountId: z.string(),
  idempotencyKey: z.string().uuid(),
}

/**
 * Builds the timestamp columns for a new outbox row.
 *
 * Postgres declares `DEFAULT now()` on these, but Zero does not consult
 * database defaults when it constructs the *optimistic client-side* row — it
 * has no connection to Postgres at that moment. Any NOT NULL column therefore
 * has to be supplied explicitly.
 *
 * The clock skew this implies is self-healing: the client writes its own
 * `Date.now()` optimistically, then the same mutator re-runs on the server
 * with the server's clock, and that authoritative row replicates back and
 * replaces the guess. This is the same reason Zero recommends client-generated
 * UUIDs — anything non-deterministic must survive being computed twice.
 */
const timestamps = () => {
  const now = Date.now()
  return {createdAt: now, updatedAt: now}
}

export const mutators = defineMutators({
  threads: {
    /**
     * Archive a thread: remove INBOX from every message in it.
     *
     * Gmail has no "archive" operation. Archiving *is* removing the INBOX
     * label — which is exactly why the schema models labels rather than
     * folders. Unarchiving is the same call with the arguments swapped.
     */
    archive: defineMutator(
      z.object({
        ...outboxArgs,
        threadId: z.string(),
        /** The account's INBOX label row id, e.g. `acct_1|INBOX`. */
        inboxLabelId: z.string(),
      }),
      async ({tx, args: {accountId, threadId, inboxLabelId, idempotencyKey}}) => {
        // Read the thread's messages so we know which junction rows to drop.
        // On the client this reads the local store and returns instantly.
        const messages = await tx.run(zql.message.where('threadId', threadId))
        if (messages.length === 0) {
          throw new Error(`archive: thread ${threadId} has no messages`)
        }

        // 1. The user-visible change: unlink INBOX from each message.
        //    The Postgres trigger decrements label.unread_count as each link
        //    disappears, so the sidebar badge follows automatically.
        for (const m of messages) {
          await tx.mutate.messageLabel.delete({id: messageLabelId(m.id, inboxLabelId)})
        }

        // 2. The remote intent — same transaction, no network call.
        //    The C++ engine picks this up and issues the actual
        //    users.messages.batchModify against the Gmail API.
        await tx.mutate.outbox.insert({
          id: idempotencyKey,
          accountId,
          op: 'modify_labels',
          payload: {
            messageIds: messages.map(m => m.remoteMessageId),
            addLabelIds: [],
            removeLabelIds: ['INBOX'],
          },
          status: 'pending',
          attempts: 0,
          idempotencyKey,
          ...timestamps(),
        })
      },
    ),

    /**
     * Mark every message in a thread read or unread.
     *
     * Note there is no explicit counter bookkeeping here. Flipping
     * `message.isRead` fires the `message_read_counts` trigger, which adjusts
     * both `label.unread_count` and `thread.unread_count`. Doing it in the
     * mutator as well would double-count.
     */
    setRead: defineMutator(
      z.object({
        ...outboxArgs,
        threadId: z.string(),
        isRead: z.boolean(),
      }),
      async ({tx, args: {accountId, threadId, isRead, idempotencyKey}}) => {
        const messages = await tx.run(
          zql.message.where('threadId', threadId).where('isRead', !isRead),
        )
        // Already in the desired state — do not emit a pointless Gmail call.
        if (messages.length === 0) {
          return
        }

        for (const m of messages) {
          await tx.mutate.message.update({id: m.id, isRead})
        }

        await tx.mutate.outbox.insert({
          id: idempotencyKey,
          accountId,
          op: 'mark_read',
          payload: {
            messageIds: messages.map(m => m.remoteMessageId),
            // UNREAD is a Gmail label, so "mark read" is a label removal.
            addLabelIds: isRead ? [] : ['UNREAD'],
            removeLabelIds: isRead ? ['UNREAD'] : [],
          },
          status: 'pending',
          attempts: 0,
          idempotencyKey,
          ...timestamps(),
        })
      },
    ),

    /** Star or unstar a thread. */
    setStarred: defineMutator(
      z.object({
        ...outboxArgs,
        threadId: z.string(),
        isStarred: z.boolean(),
      }),
      async ({tx, args: {accountId, threadId, isStarred, idempotencyKey}}) => {
        const thread = await tx.run(zql.thread.where('id', threadId).one())
        if (!thread) {
          throw new Error(`setStarred: unknown thread ${threadId}`)
        }

        await tx.mutate.thread.update({id: threadId, isStarred})

        const messages = await tx.run(zql.message.where('threadId', threadId))
        for (const m of messages) {
          await tx.mutate.message.update({id: m.id, isStarred})
        }

        await tx.mutate.outbox.insert({
          id: idempotencyKey,
          accountId,
          op: 'modify_labels',
          payload: {
            messageIds: messages.map(m => m.remoteMessageId),
            addLabelIds: isStarred ? ['STARRED'] : [],
            removeLabelIds: isStarred ? [] : ['STARRED'],
          },
          status: 'pending',
          attempts: 0,
          idempotencyKey,
          ...timestamps(),
        })
      },
    ),
  },

  outbox: {
    /**
     * Retry a permanently-failed operation.
     *
     * Resetting `status` to `pending` is all that is needed — the C++ engine
     * polls for pending work, so this hands the row straight back to it.
     */
    retry: defineMutator(z.object({id: z.string()}), async ({tx, args: {id}}) => {
      const row = await tx.run(zql.outbox.where('id', id).one())
      if (!row || row.status !== 'failed') {
        return
      }
      await tx.mutate.outbox.update({id, status: 'pending', attempts: 0, lastError: null})
    }),
  },
})
