/**
 * Zero mutators — every write in the application.
 *
 * ## The rule these are all built around
 *
 * A mutator must never perform network I/O. It is a fast, purely-local,
 * transactional operation. Gmail side effects are recorded as rows in the
 * `outbox` table *inside the same transaction* as the user-visible state
 * change, and drained later by the C++ engine.
 *
 * That is what makes optimistic UI correct rather than a lie:
 *
 *   - The local write lands in the same frame, so the UI moves instantly.
 *   - The state change and its remote intent commit atomically, so a crash can
 *     never leave the mailbox archived locally but not on Gmail.
 *   - The outbox row is durable and retryable, so a flaky network is a delay
 *     rather than a lost operation.
 *
 * ## Life of a mutation
 *
 * Each mutator runs twice. First on the client against the local store, where
 * its effects are immediately visible. Then on the server against Postgres,
 * where it is authoritative. The server's result replicates back and replaces
 * the client's optimistic guess. Reads inside a mutator see only local data on
 * the client (`tx.location === 'client'`) and all data on the server.
 */

import {defineMutator, defineMutators} from '@rocicorp/zero'
import {z} from 'zod'
import {messageLabelId} from './ids.ts'
import {zql} from './schema.ts'

/**
 * Arguments shared by every outbox-producing mutator.
 *
 * `idempotencyKey` is generated by the *client* (`crypto.randomUUID()`) and
 * passed through. Because the mutator runs on both client and server with the
 * same key, a retried mutation collapses onto the same outbox row instead of
 * sending the same Gmail call twice.
 */
const outboxArgs = {
  accountId: z.string(),
  idempotencyKey: z.string().uuid(),
}

/**
 * Builds the timestamp columns for a new outbox row.
 *
 * Postgres declares `DEFAULT now()` on these, but Zero does not consult
 * database defaults when it constructs the *optimistic client-side* row — it
 * has no connection to Postgres at that moment. Any NOT NULL column therefore
 * has to be supplied explicitly.
 *
 * The clock skew this implies is self-healing: the client writes its own
 * `Date.now()` optimistically, then the same mutator re-runs on the server
 * with the server's clock, and that authoritative row replicates back and
 * replaces the guess. This is the same reason Zero recommends client-generated
 * UUIDs — anything non-deterministic must survive being computed twice.
 */
const timestamps = () => {
  const now = Date.now()
  return {createdAt: now, updatedAt: now}
}

export const mutators = defineMutators({
  threads: {
    /**
     * Archive a thread: remove INBOX from every message in it.
     *
     * Gmail has no "archive" operation. Archiving *is* removing the INBOX
     * label — which is exactly why the schema models labels rather than
     * folders. Unarchiving is the same call with the arguments swapped.
     */
    archive: defineMutator(
      z.object({
        ...outboxArgs,
        threadId: z.string(),
        /** The account's INBOX label row id, e.g. `acct_1|INBOX`. */
        inboxLabelId: z.string(),
      }),
      async ({tx, args: {accountId, threadId, inboxLabelId, idempotencyKey}}) => {
        // Read the thread's messages so we know which junction rows to drop.
        // On the client this reads the local store and returns instantly.
        const messages = await tx.run(zql.message.where('threadId', threadId))
        if (messages.length === 0) {
          throw new Error(`archive: thread ${threadId} has no messages`)
        }

        // 1. The user-visible change: unlink INBOX from each message.
        //    The Postgres trigger decrements label.unread_count as each link
        //    disappears, so the sidebar badge follows automatically.
        for (const m of messages) {
          await tx.mutate.messageLabel.delete({id: messageLabelId(m.id, inboxLabelId)})
        }

        // 2. The remote intent — same transaction, no network call.
        //    The C++ engine picks this up and issues the actual
        //    users.messages.batchModify against the Gmail API.
        await tx.mutate.outbox.insert({
          id: idempotencyKey,
          accountId,
          op: 'modify_labels',
          payload: {
            messageIds: messages.map(m => m.remoteMessageId),
            addLabelIds: [],
            removeLabelIds: ['INBOX'],
          },
          status: 'pending',
          attempts: 0,
          idempotencyKey,
          ...timestamps(),
        })
      },
    ),

    /**
     * Mark every message in a thread read or unread.
     *
     * Note there is no explicit counter bookkeeping here. Flipping
     * `message.isRead` fires the `message_read_counts` trigger, which adjusts
     * both `label.unread_count` and `thread.unread_count`. Doing it in the
     * mutator as well would double-count.
     */
    setRead: defineMutator(
      z.object({
        ...outboxArgs,
        threadId: z.string(),
        isRead: z.boolean(),
      }),
      async ({tx, args: {accountId, threadId, isRead, idempotencyKey}}) => {
        const messages = await tx.run(
          zql.message.where('threadId', threadId).where('isRead', !isRead),
        )
        // Already in the desired state — do not emit a pointless Gmail call.
        if (messages.length === 0) {
          return
        }

        for (const m of messages) {
          await tx.mutate.message.update({id: m.id, isRead})
        }

        await tx.mutate.outbox.insert({
          id: idempotencyKey,
          accountId,
          op: 'mark_read',
          payload: {
            messageIds: messages.map(m => m.remoteMessageId),
            // UNREAD is a Gmail label, so "mark read" is a label removal.
            addLabelIds: isRead ? [] : ['UNREAD'],
            removeLabelIds: isRead ? ['UNREAD'] : [],
          },
          status: 'pending',
          attempts: 0,
          idempotencyKey,
          ...timestamps(),
        })
      },
    ),

    /** Star or unstar a thread. */
    setStarred: defineMutator(
      z.object({
        ...outboxArgs,
        threadId: z.string(),
        isStarred: z.boolean(),
      }),
      async ({tx, args: {accountId, threadId, isStarred, idempotencyKey}}) => {
        const thread = await tx.run(zql.thread.where('id', threadId).one())
        if (!thread) {
          throw new Error(`setStarred: unknown thread ${threadId}`)
        }

        await tx.mutate.thread.update({id: threadId, isStarred})

        const messages = await tx.run(zql.message.where('threadId', threadId))
        for (const m of messages) {
          await tx.mutate.message.update({id: m.id, isStarred})
        }

        await tx.mutate.outbox.insert({
          id: idempotencyKey,
          accountId,
          op: 'modify_labels',
          payload: {
            messageIds: messages.map(m => m.remoteMessageId),
            addLabelIds: isStarred ? ['STARRED'] : [],
            removeLabelIds: isStarred ? [] : ['STARRED'],
          },
          status: 'pending',
          attempts: 0,
          idempotencyKey,
          ...timestamps(),
        })
      },
    ),
  },

  compose: {
    /**
     * Queues a message.
     *
     * One mutator for replies and new messages alike: the only difference is
     * whether the threading fields are populated, and duplicating everything
     * else to express that would mean two code paths that must not drift.
     *
     * Writes ONLY an outbox row — no local message is inserted. A sent message
     * comes back from Gmail on the next poll as a real message with a real id,
     * and inserting an optimistic copy first would duplicate it, or leave an
     * orphan if the send failed. The trade is a short delay before it appears
     * in the thread, which is honest.
     *
     * Threading headers are supplied by the CLIENT because it already has the
     * conversation loaded; the engine would otherwise re-fetch the parent
     * purely to read its Message-ID.
     */
    send: defineMutator(
      z.object({
        ...outboxArgs,
        fromName: z.string(),
        fromEmail: z.string().email(),
        to: z.array(z.string().email()).min(1),
        cc: z.array(z.string().email()).default([]),
        subject: z.string(),
        body: z.string().min(1),

        /**
         * Threading. All absent for a new message.
         *
         * `remoteThreadId` is Gmail's own id, which is what makes a reply land
         * in the existing conversation in Gmail's UI. The In-Reply-To and
         * References headers do the same job for every OTHER mail client, so
         * both are needed — neither is redundant.
         */
        remoteThreadId: z.string().default(''),
        inReplyTo: z.string().default(''),
        references: z.array(z.string()).default([]),
      }),
      async ({tx, args}) => {
        const {accountId, idempotencyKey, ...draft} = args

        await tx.mutate.outbox.insert({
          id: idempotencyKey,
          accountId,
          op: 'send',
          payload: {
            threadId: draft.remoteThreadId,
            fromName: draft.fromName,
            fromEmail: draft.fromEmail,
            to: draft.to,
            cc: draft.cc,
            subject: draft.subject,
            body: draft.body,
            inReplyTo: draft.inReplyTo,
            references: draft.references,
          },
          status: 'pending',
          attempts: 0,
          idempotencyKey,
          ...timestamps(),
        })
      },
    ),
  },

  attachments: {
    /**
     * Requests an attachment's bytes.
     *
     * Like every other outbox op, this only records intent — the engine owns
     * all network I/O. What comes back is a `localPath` on the attachment row,
     * not the bytes: the file goes to a content-addressed cache on disk,
     * because anything written to Postgres is replicated into zero-cache's
     * SQLite replica and diffed on every sync. 465 MB of attachments there
     * would destroy the thing that makes reads instant.
     *
     * Deliberately does NOT skip when `localPath` is already set. The cache
     * lives under `~/Library/Caches`, which macOS may reclaim at any time, so
     * a recorded path can outlive its file. The caller checks the disk and
     * asks again if the file is gone; the engine re-checks too and skips the
     * transfer when the blob is genuinely still there.
     */
    download: defineMutator(
      z.object({
        accountId: z.string(),
        attachmentId: z.string(),
      }),
      async ({tx, args: {accountId, attachmentId}}) => {
        const attachment = await tx.run(zql.attachment.where('id', attachmentId).one())
        if (!attachment) {
          throw new Error(`download: unknown attachment ${attachmentId}`)
        }
        if (!attachment.remoteAttachmentId) {
          // Gmail inlines very small parts into the message body rather than
          // exposing an attachment id. There is nothing to fetch.
          throw new Error(`download: attachment ${attachmentId} has no remote id`)
        }

        // The outbox id is derived from the attachment rather than random, so
        // that clicking a chip five times queues one download instead of five.
        // Every other op uses a client-generated UUID because two archives of
        // the same thread are two distinct intents; two downloads of the same
        // file are not.
        const id = `download|${attachmentId}`

        const existing = await tx.run(zql.outbox.where('id', id).one())
        if (existing) {
          // Already queued or being worked on — leave it alone.
          if (existing.status === 'pending' || existing.status === 'in_flight') {
            return
          }
          // Previously done or failed: hand it back to the drainer. This is
          // what makes a retry after a cache purge, or after a network
          // failure, just another click.
          await tx.mutate.outbox.update({
            id,
            status: 'pending',
            attempts: 0,
            lastError: null,
            updatedAt: Date.now(),
          })
          return
        }

        await tx.mutate.outbox.insert({
          id,
          accountId,
          op: 'download_attachment',
          payload: {attachmentId},
          status: 'pending',
          attempts: 0,
          idempotencyKey: id,
          ...timestamps(),
        })
      },
    ),
  },

  accounts: {
    /**
     * Renames or recolours a connected mailbox.
     *
     * Purely local presentation — nothing here touches Gmail, so unlike almost
     * every other mutator in this file it writes NO outbox row. `display_name`
     * is seeded from the address on first sync, which is why every account
     * starts out labelled with its own local part.
     *
     * The colour is what makes a unified inbox readable once several accounts
     * are merged into one list, so it is worth letting people choose one they
     * can actually tell apart.
     */
    update: defineMutator(
      z.object({
        accountId: z.string(),
        displayName: z.string().trim().min(1).max(64).optional(),
        // Hex, validated here rather than at the view: a malformed value would
        // otherwise reach every client through replication and each would have
        // to defend against it separately.
        color: z.string().regex(/^#[0-9a-fA-F]{6}$/).optional(),
      }),
      async ({tx, args: {accountId, displayName, color}}) => {
        const account = await tx.run(zql.account.where('id', accountId).one())
        if (!account) {
          throw new Error(`update: unknown account ${accountId}`)
        }
        await tx.mutate.account.update({
          id: accountId,
          ...(displayName === undefined ? {} : {displayName}),
          ...(color === undefined ? {} : {color: color.toLowerCase()}),
        })
      },
    ),
  },

  outbox: {
    /**
     * Retry a permanently-failed operation.
     *
     * Resetting `status` to `pending` is all that is needed — the C++ engine
     * polls for pending work, so this hands the row straight back to it.
     */
    retry: defineMutator(z.object({id: z.string()}), async ({tx, args: {id}}) => {
      const row = await tx.run(zql.outbox.where('id', id).one())
      if (!row || row.status !== 'failed') {
        return
      }
      await tx.mutate.outbox.update({id, status: 'pending', attempts: 0, lastError: null})
    }),
  },
})
